// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DataRepository is an autogenerated mock type for the DataRepository type
type DataRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, address, key
func (_m *DataRepository) Get(ctx context.Context, address string, key string) (string, error) {
	ret := _m.Called(ctx, address, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, address, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, address, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, address, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDataRepository creates a new instance of DataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataRepository {
	mock := &DataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
